amp:
  opt_level: O0
  sync_bn: true
checkpoint:
  ckpt_path: /shared/jacklishufan/ckpt/detconb/{}/{}_{}_{}.pth.tar
  resume_path:  
  save_epoch: 10
  time_stamp: null
clustering:
  add_views: true
  batch_size: 0
  gather: false
  no_slic: true
  superpixel: slic # switch SLIC vs FH
  per_image: false
  scheduler:
    epochs:
    - 0
    - 300
    type: cosine
    values:
    - 128
    - 128
  use_pca: 0
  weight_color: 0.0
  weight_spatial: 0.0
  spatial_resolution: 10
data:
  data_workers: 8
  dual_views: true
  image_dir: ./imagenet
  mask_type: ''
  n_kmeans: 9999
  num_examples: 1281167
  over_lap_mask: false
  overlap_indicator: true
  resize_size: 224
  slic_segments: 100
  subset: "imagenet100"
  train_batch_size: 256
  val_batch_size: 32
  weight: false
distributed: true
local_rank: 0
log:
  log_all: false
  log_dir: null
  log_step: 10
  enable_wandb: True
loss:
  mask_rois: 16
  temperature: 0.1
  type: byol
model:
  backbone:
    pretrained: false
    type: resnet50
  base_momentum: 0.99
  masknet: false
  predictor:
    hidden_dim: 4096
    input_dim: 256
    output_dim: 256
    type: MLP
  projection:
    hidden_dim: [4096] #[4096,2048,1024]
    input_dim: [2048]
    output_dim: 256
    keys: [c5]
    type: MLP
  projection_map:
    c5: c5
    c6: c5
    c7: c5
    c8: c5
  loss_weight:
    c5: 0.2
    c6: 1.0
    c7: 1.0
    c8: 1.0
  random_mask_p: 1.0

optimizer:
  base_lr: 0.3
  exclude_bias_and_bn: true
  legacy_schedule: false
  lr_type: cosine
  momentum: 0.9
  scheduler:
    epochs:
    - 0
    - 100
    type: cosine
    values:
    - 1.0
    - 0
  total_epochs: 300
  scale_lr_by_k: 32
  type: lars
  warmup_epochs: 3
  weight_decay: 1.0e-06
rank: 0
seed: 0
stage: train
world_size: 8

eval:
  img_dir: ./imagenet/images
  knn: 20 # 0 to disable
  eval_step: 5