amp:
  opt_level: O0
  sync_bn: true
checkpoint:
  ckpt_path: /shared/jacklishufan/ckpt/detconb/{}/{}_{}_{}.pth.tar
  resume_path: null
  save_epoch: 50
  time_stamp: null
clustering:
  add_views: false
  batch_size: 0
  gather: false
  no_slic: true
  per_image: false
  spatial_dimension: [12,4,1]
  spatial_dimension_weights: [1.0,2.0,3.0]
  spatial_dimension_projection_idx: [0,1,2] # [0,1,..model.projection.n_projection - 1], [0,0,0] means shared projection heads
  random_p: 1.0
  scheduler:
    epochs:
    - 0
    - 300
    type: cosine
    values:
    - 9999
    - 9999
  sub_sample_size: 0
  superpixel: slic
  use_pca: 0
  weight_color: 0.0
  weight_spatial: 0.0
data:
  data_workers: 16
  dual_views: true
  image_dir: /home/jacklishufan/detconb/imagenet
  mask_type: ''
  n_kmeans: 9999
  num_examples: 1281167
  over_lap_mask: false
  overlap_indicator: true
  resize_size: 224
  slic_segments: 100
  subset: imagenet100
  train_batch_size: 128
  val_batch_size: 32
  weight: false
distributed: true
eval:
  eval_step: 5
  img_dir:  /home/jacklishufan/detconb/imagenet/images
  knn: 20
local_rank: 3
log:
  enable_wandb: true
  log_all: false
  log_dir: null
  log_step: 10
loss:
  mask_rois: 16
  temperature: 0.1
  type: byol
model:
  backbone:
    pretrained: false
    type: resnet50
  base_momentum: 0.99
  masknet: false
  predictor:
    hidden_dim: 4096
    input_dim: 256
    output_dim: 256
    type: MLP
  projection:
    hidden_dim: 4096
    input_dim: 2048
    output_dim: 256
    n_projection: 3
    type: MLP
optimizer:
  base_lr: 0.3
  exclude_bias_and_bn: true
  legacy_schedule: false
  lr_type: cosine
  momentum: 0.9
  scale_lr_by_k: 16
  scheduler:
    epochs:
    - 0
    - 100
    type: cosine
    values:
    - 1
    - 0
  total_epochs: 300
  type: lars
  warmup_epochs: 3
  weight_decay: 1.0e-06
rank: 7
seed: 0
stage: train
world_size: 128