model:
  base_momentum: 0.99
  masknet: false
  backbone:
    type: "resnet50"
    pretrained: false
  projection:   # src: A.2 of detcon paper
    type: "MLP" 
    input_dim: 2048
    hidden_dim: 4096
    output_dim: 256
  predictor:
    type: "MLP"
    input_dim: 256
    hidden_dim: 4096
    output_dim: 256

amp:
  sync_bn: True
  opt_level: "O0"

data:
  image_dir: "/home/acb11129ts/workspace/ssl/BYOL-PyTorch-master/dataset/imagenet/" #TODO: Change to match Japan Cluster
  subset: "imagenet" #Set to imagenet100 for imagenet100 or imagenet1p for 1p. "" = full imagenet
  mask_type: ""
  resize_size: 224 # src: 3.1
  data_workers: 24
  overlap_indicator: true 
  weight: false
  n_kmeans: 64
  slic_segments: 100
  train_batch_size: 32 # src: A.3 (Global should be 4096 = batch_size x num_gpu)
  val_batch_size: 32 #  Should not matter
  dual_views: true
  over_lap_mask: false
  num_examples: 1281167 #For imagenet1p, imagenet100, byol_trainer automatically updates num_examples accordingly

optimizer:
  type: lars
  base_lr: 0.3
  lr_type: "cosine"
  momentum: 0.9 # src: Deepmind code config
  weight_decay: 1.0e-6
  total_epochs: 300
  warmup_epochs: 3 # src: Deepmind code; should be 1/100 of total epoches
  exclude_bias_and_bn: true

loss: #src: 3.1
  temperature: 0.1
  mask_rois: 16

checkpoint:
  time_stamp:
  resume_path:
  save_epoch: 50
  ckpt_path: "/projects/d001/gce50852/ssl/pretrain/ckpt/detconb_imagenet/{}/{}_{}_{}.pth.tar"

log:
  log_step: 10
  log_dir:
  log_all: False

stage: "train"
distributed: True
seed: 0
