model:
  base_momentum: 0.99
  backbone:
    type: "resnet50"
    pretrained: false
  projection:   # src: A.2 of detcon paper
    type: "MLP" 
    input_dim: 2048
    hidden_dim: 4096
    output_dim: 256
  predictor:
    type: "MLP"
    input_dim: 256
    hidden_dim: 4096
    output_dim: 256
  memory_size: 2048

amp:
  sync_bn: True
  opt_level: "O0"

data:
  image_dir: ""
  mask_type: "fh"
  resize_size: 224
  data_workers: 16
  train_batch_size: 64
  val_batch_size: 32
  dual_views: true
  num_examples: 118287 #1281167

optimizer:
  type: lars
  base_lr: 0.3
  lr_type: "piecewise"
  momentum: 0.9
  weight_decay: 1.0e-6
  total_epochs: 300
  warmup_epochs: 3 # should be 1/100 of total epoches

stage: "train"
seed: 0
distributed: True