amp:
  opt_level: O0
  sync_bn: true
checkpoint:
  ckpt_path: "/shared/jacklishufan/ckpt/detconb/{}/{}_{}_{}.pth.tar"
  resume_path: 
  save_epoch: 50
  time_stamp: null
clustering:
  add_views: false
  gather: false
  no_slic: false
  superpixel: slic # switch SLIC vs FH
  per_image: false
  batch_size: 32
  sub_sample_size: 16 # subsampl masks, 0 disable
  scheduler:
    epochs:
    - 0
    - 300
    type: random
    values:
    - 16
    - 160
  use_pca: 0
  weight_color: 0.0
  weight_spatial: 0.0
data:
  data_workers: 8
  dual_views: true
  image_dir: "./coco"
  mask_type: 'coco'
  n_kmeans: 9999
  num_examples: 117266
  over_lap_mask: false
  overlap_indicator: true
  resize_size: 224
  slic_segments: 100
  subset: ""
  train_batch_size: 128
  val_batch_size: 32
  weight: false
distributed: true
local_rank: 0
log:
  enable_wandb: on
  log_all: false
  log_dir: null
  log_step: 10
loss:
  type: byol
  mask_rois: 16
  temperature: 0.1
model:
  backbone:
    pretrained: false
    type: resnet50
  base_momentum: 0.99
  masknet: false
  predictor:
    hidden_dim: 4096
    input_dim: 256
    output_dim: 256
    type: MLP
  projection:
    hidden_dim: 4096
    input_dim: 2048
    output_dim: 256
    type: MLP
optimizer:
  base_lr: 0.3
  scale_lr_by_k: 0 #scale lr based on a base clustering_k, 0 to disable
  exclude_bias_and_bn: true
  legacy_schedule: false
  lr_type: cosine
  momentum: 0.9
  scheduler:
    epochs:
    - 0
    - 100 
    type: cosine
    values:
    - 1
    - 0
  total_epochs: 100
  type: lars
  warmup_epochs: 8
  weight_decay: 1.0e-06
rank: 0
seed: 0
stage: train

eval:
  img_dir: ./imagenet/images
  knn: 20 # 0 to disable
  eval_step: 5