model:
  base_momentum: 0.99
  backbone:
    type: "resnet50"
    pretrained: false
  projection:   # src: A.2 of detcon paper
    type: "MLP" 
    input_dim: 2048
    hidden_dim: 4096
    output_dim: 256
  predictor:
    type: "MLP"
    input_dim: 256
    hidden_dim: 4096
    output_dim: 256

amp:
  sync_bn: True
  opt_level: "O0"

data:
  image_dir: "/home/kkallidromitis/data/coco/" #TODO: Change to match Japan Cluster
  mask_type: "fh"
  resize_size: 224 # src: 3.1
  data_workers: 16
  train_batch_size: 4096 # src: A.3
  val_batch_size: 2048 #  Should not matter
  dual_views: true
  num_examples: 118287 # TODO: Change according to ImageNet 

optimizer:
  type: lars
  base_lr: 0.3
  momentum:  0.99 # src: A.2
  weight_decay: 1.0e-6
  total_epochs: 300
  warmup_epochs: 30 # src: Deepmind code; should be 1/10 of total epoches
  exclude_bias_and_bn: true

loss: #src: 3.1
  temperature: 0.1
  mask_rois: 16

checkpoint:
  time_stamp:
  resume_path:
  save_epoch: 10
  ckpt_path: "ckpt/detconb/{}/{}_{}.pth.tar"

log:
  log_step: 10
  log_dir:

stage: "train"
distributed: true
seed: 0
