model:
  base_momentum: 0.99
  backbone:
    type: "resnet50"
    pretrained: false
  projection:   # src: A.2 of detcon paper
    type: "MLP" 
    input_dim: 2048
    hidden_dim: 4096
    output_dim: 256
  predictor:
    type: "MLP"
    input_dim: 256
    hidden_dim: 4096
    output_dim: 256
  memory_size: 2048

amp:
  sync_bn: True
  opt_level: "O0"

data:
  image_dir: "/home/akash/ilsvrc_1p" #TODO: Change to match Japan Cluster
  resize_size: 224 # src: 3.1
  data_workers: 16
  train_batch_size: 32 # src: A.3 (Global should be 4096 = batch_size x num_gpu)
  val_batch_size: 32 #  Should not matter
  dual_views: true
  num_examples: 12811

optimizer:
  type: lars
  base_lr: 0.3
  momentum: 0.9 # src: Deepmind code config
  weight_decay: 1.0e-6
  total_epochs: 300
  warmup_epochs: 3 # src: Deepmind code; should be 1/100 of total epoches
  exclude_bias_and_bn: true

checkpoint:
  time_stamp:
  resume_path:
  save_epoch: 50
  ckpt_path: "ckpt/byol/{}/{}_{}_{}.pth.tar"

log:
  log_step: 10
  log_dir:
  log_all: False

stage: "train"
distributed: True
seed: 0
